### ISSUE TITLE
Smart imports

### ISSUE THREAD

**Issue by srghma** [natefaubion/purescript-tidy-codegen#15]
I want to be able to gen code

```purs
main = log "asdfasdf"
```

but I want to be able to attach meta info to the `log` function that this function is from `Effect.Console` module

and `tidy-codegen` would print module with generated imports 

```purs
import Effect.Console (log)

main = log "asdfasdf"
```

----------

how this is impl in ps-cst (which I wrote, but I'm sure, You, Nathan would write better :) )

this file https://github.com/purescript-codegen/purescript-ps-cst/blob/master/src/Language/PS/SmartCST/Sugar/Declaration.purs is just this file https://github.com/purescript-codegen/purescript-ps-cst/blob/master/src/Language/PS/CST/Sugar/Declaration.purs , but after https://github.com/purescript-codegen/purescript-ps-cst/blob/master/sync-cst-declaration-to-smart-cst.sh

I'm just replacing

```
sed -i 's/QualifiedName (ProperName ProperNameType_ConstructorName)/SmartQualifiedNameConstructor/g' src/Language/PS/SmartCST/Types/Declaration.purs
sed -i 's/QualifiedName/SmartQualifiedName/g' src/Language/PS/SmartCST/Types/Declaration.purs
```

main types are

https://github.com/purescript-codegen/purescript-ps-cst/blob/master/src/Language/PS/SmartCST/Types/SmartQualifiedName.purs#L9-L29

https://github.com/purescript-codegen/purescript-ps-cst/blob/master/src/Language/PS/SmartCST/Types/SmartQualifiedNameConstructor.purs#L13-L36

and a function that collects all imports before printing

https://github.com/purescript-codegen/purescript-ps-cst/blob/master/src/Language/PS/SmartCST/ProcessSmartDeclaration.purs#L128-L187

-------

how this is used

https://github.com/purescript-graphqlclient/purescript-graphqlclient/blob/3c833446aa0b16b07dfd2cc61c5adbdddb800280/generator/GraphQLClientGenerator/MakeModule/Enum.purs#L50 `String` is from Prim, so there are no imports

https://github.com/purescript-graphqlclient/purescript-graphqlclient/blob/3c833446aa0b16b07dfd2cc61c5adbdddb800280/generator/GraphQLClientGenerator/MakeModule/Enum.purs#L80 -- this will gen imports

**Comment by natefaubion** [comment]
Currently, the way to accomplish this is with `CodegenT` in `Tidy.Codegen.Monad` which is used to manage imports and exports. You'd do something like:

```purescript
example = do
  log  <- importFrom "Effect.Console" (importValue "log")
  lookup <- importFrom "Data.Map" (importValue "Map.lookup") -- imports qualified
  ...
```

It gives you a name back and tracks the import for you. You can also use this to import qualified (there are a few examples in the docs for `importFrom`).

I like the annotations approach, but the CST types don't support arbitrary annotations. I opted to support error recovery, and so the type parameter is used for that. One possibility is in the future, CST types could take a functor parameter which could be used as a fix point. That could make arbitrary annotations possible and still support error nodes.

**Comment by srghma** [comment]
good that this is already implemented, tnx!
