### ISSUE TITLE
Problem with imported type operators

### ISSUE THREAD

**Issue by blinky3713** [natefaubion/purescript-tidy-codegen#5]
If I use `Monad.importFrom` with `Monad.importTypeOp`, I'm getting that the return value is still rendering with parens. 

The following code produces the following error:

![image](https://user-images.githubusercontent.com/31280145/136475686-7299bfed-3b8f-4709-b0b1-812575bf1bbb.png)

![image](https://user-images.githubusercontent.com/31280145/136475706-bf970d05-f941-47dc-b907-2d717ef05412.png)

The current solution is just to ignore the return value of the import statement completely and just use `":&"` directly wherever it would have been used

**Comment by natefaubion** [comment]
Normal operator imports are broken as well 😱
